app.constant('SongData',
[
  {
    "attribute": "Smile",
    "easy_notes": 101,
    "expert_notes": 515,
    "hard_notes": 330,
    "main_unit": "Aqours",
    "master_notes": null,
    "name": "AqoursâHEROES",
    "normal_notes": 207,
    "romaji_name": null,
    "time": 115,
    "translated_name": null
  },
  {
    "attribute": "Cool",
    "easy_notes": 106,
    "expert_notes": 584,
    "hard_notes": 390,
    "main_unit": "Aqours",
    "master_notes": null,
    "name": "Step! ZERO to ONE",
    "normal_notes": 218,
    "romaji_name": null,
    "time": 119,
    "translated_name": null
  },
  {
    "attribute": "Cool",
    "easy_notes": 102,
    "expert_notes": 535,
    "hard_notes": 360,
    "main_unit": "Aqours",
    "master_notes": null,
    "name": "Strawberry Trapper",
    "normal_notes": 175,
    "romaji_name": null,
    "time": 101,
    "translated_name": null
  },
  {
    "attribute": "Cool",
    "easy_notes": 81,
    "expert_notes": 371,
    "hard_notes": 259,
    "main_unit": "Aqours",
    "master_notes": null,
    "name": "ã¨ãããåé¡å­¦",
    "normal_notes": 146,
    "romaji_name": "Tokimeki Bunruigaku",
    "time": 123,
    "translated_name": "The Taxonomy of Excitement"
  },
  {
    "attribute": "Pure",
    "easy_notes": 100,
    "expert_notes": 478,
    "hard_notes": 331,
    "main_unit": "Aqours",
    "master_notes": null,
    "name": "ããªã³ãªã³PLEASE!!",
    "normal_notes": 195,
    "romaji_name": "Torikoriko PLEASE!!",
    "time": 103,
    "translated_name": "Please Let Me Capture Your Heart!!"
  },
  {
    "attribute": "Smile",
    "easy_notes": 95,
    "expert_notes": 348,
    "hard_notes": 181,
    "main_unit": "Î¼'s",
    "master_notes": 697,
    "name": "åãã®LIVE åã¨ã®LIFE",
    "normal_notes": 120,
    "romaji_name": "Bokura no LIVE Kimi to no LIFE",
    "time": 125,
    "translated_name": "Our Live, Life with You"
  },
  {
    "attribute": "Smile",
    "easy_notes": 120,
    "expert_notes": 592,
    "hard_notes": 412,
    "main_unit": "Aqours",
    "master_notes": null,
    "name": "åæ°å¨éDAY!DAY!DAY!",
    "normal_notes": 228,
    "romaji_name": "Genki Zenkai DAY! DAY! DAY!",
    "time": 126,
    "translated_name": "Full Throttle Energy DAY! DAY! DAY!"
  },
  {
    "attribute": "Pure",
    "easy_notes": 112,
    "expert_notes": 497,
    "hard_notes": 359,
    "main_unit": "Aqours",
    "master_notes": null,
    "name": "åã®ãããã¯è¼ãã¦ããã?",
    "normal_notes": 201,
    "romaji_name": "Kimi no Kokoro wa Kagayaiteru kai?",
    "time": 120,
    "translated_name": "Is Your Heart Shining?"
  },
  {
    "attribute": "Smile",
    "easy_notes": 122,
    "expert_notes": 563,
    "hard_notes": 407,
    "main_unit": "Aqours",
    "master_notes": null,
    "name": "å±ããªãæã ã¨ãã¦ã",
    "normal_notes": 224,
    "romaji_name": "Todokanai Hoshi da to Shitemo",
    "time": 126,
    "translated_name": "Even if Its an Unreachable Star"
  },
  {
    "attribute": "Pure",
    "easy_notes": 95,
    "expert_notes": 466,
    "hard_notes": 334,
    "main_unit": "Aqours",
    "master_notes": null,
    "name": "å¾ã£ã¦ã¦æã®ãã",
    "normal_notes": 164,
    "romaji_name": "Mattete Ai no Uta",
    "time": 125,
    "translated_name": "Wait for Me: A Love Song"
  },
  {
    "attribute": "Cool",
    "easy_notes": 108,
    "expert_notes": 544,
    "hard_notes": 379,
    "main_unit": "Aqours",
    "master_notes": null,
    "name": "æã«ãªãããAQUARIUM",
    "normal_notes": 184,
    "romaji_name": "Koi ni Naritai AQUARIUM",
    "time": 123,
    "translated_name": "I Want Love to Bloom at the Aquarium"
  },
  {
    "attribute": "Pure",
    "easy_notes": 91,
    "expert_notes": 359,
    "hard_notes": 204,
    "main_unit": "Î¼'s",
    "master_notes": 640,
    "name": "åæãã¼ãã§ã³ã¸",
    "normal_notes": 125,
    "romaji_name": "Yuujou No Change",
    "time": 124,
    "translated_name": "Unchanging Friendship"
  },
  {
    "attribute": "Pure",
    "easy_notes": 97,
    "expert_notes": 362,
    "hard_notes": 220,
    "main_unit": "Î¼'s",
    "master_notes": null,
    "name": "baby maybe æã®ãã¿ã³",
    "normal_notes": 148,
    "romaji_name": "baby maybe Koi no Button",
    "time": 125,
    "translated_name": "baby maybe Button of Love"
  },
  {
    "attribute": "Cool",
    "easy_notes": 81,
    "expert_notes": 355,
    "hard_notes": 206,
    "main_unit": "Î¼'s",
    "master_notes": 551,
    "name": "Snow halation",
    "normal_notes": 139,
    "romaji_name": null,
    "time": 123,
    "translated_name": null
  },
  {
    "attribute": "Smile",
    "easy_notes": 105,
    "expert_notes": 471,
    "hard_notes": 360,
    "main_unit": "Aqours",
    "master_notes": null,
    "name": "éç©ºJumping Heart",
    "normal_notes": 208,
    "romaji_name": "Aozora Jumping Heart",
    "time": 97,
    "translated_name": "Blue Sky Jumping Heart"
  },
  {
    "attribute": "Pure",
    "easy_notes": 106,
    "expert_notes": 471,
    "hard_notes": 329,
    "main_unit": "Aqours",
    "master_notes": null,
    "name": "ã¦ã¡èªãããã¦ã¡æ­ãã",
    "normal_notes": 187,
    "romaji_name": "Yume Kataru yori Yume Utaou",
    "time": 106,
    "translated_name": "Sing Your Dreams Instead of Talking about Them"
  },
  {
    "attribute": "Cool",
    "easy_notes": 99,
    "expert_notes": 431,
    "hard_notes": 237,
    "main_unit": "Î¼'s",
    "master_notes": null,
    "name": "Mermaid festa vol.1",
    "normal_notes": 158,
    "romaji_name": null,
    "time": 121,
    "translated_name": null
  },
  {
    "attribute": "Smile",
    "easy_notes": 85,
    "expert_notes": 370,
    "hard_notes": 225,
    "main_unit": "Î¼'s",
    "master_notes": 786,
    "name": "å¤è²ãããã§1,2,Jump!",
    "normal_notes": 146,
    "romaji_name": "Natsu-iro Egao de 1, 2, Jump!",
    "time": 125,
    "translated_name": "1, 2, Jump with a Summer-Colored Smile!"
  },
  {
    "attribute": "Pure",
    "easy_notes": 89,
    "expert_notes": 391,
    "hard_notes": 224,
    "main_unit": "Î¼'s",
    "master_notes": 575,
    "name": "ãããã£ã¨\"love\"ã§æ¥è¿ä¸­!",
    "normal_notes": 143,
    "romaji_name": "Mogyutto love de Sekkinchuu!",
    "time": 125,
    "translated_name": "Grab Tightly When Getting Closer to Love!"
  },
  {
    "attribute": "Smile",
    "easy_notes": 90,
    "expert_notes": 302,
    "hard_notes": 223,
    "main_unit": "Î¼'s",
    "master_notes": null,
    "name": "æãã¦ãã°ããã¼ã!",
    "normal_notes": 164,
    "romaji_name": "Aishiteru Banzai!",
    "time": 112,
    "translated_name": "I Love You, Hooray!"
  },
  {
    "attribute": "Smile",
    "easy_notes": 113,
    "expert_notes": 457,
    "hard_notes": 255,
    "main_unit": "Î¼'s",
    "master_notes": null,
    "name": "Oh,Love&Peace!",
    "normal_notes": 183,
    "romaji_name": null,
    "time": 125,
    "translated_name": null
  },
  {
    "attribute": "Cool",
    "easy_notes": 111,
    "expert_notes": 386,
    "hard_notes": 247,
    "main_unit": "Î¼'s",
    "master_notes": 616,
    "name": "Wonderful Rush",
    "normal_notes": 172,
    "romaji_name": null,
    "time": 113,
    "translated_name": null
  },
  {
    "attribute": "Smile",
    "easy_notes": 110,
    "expert_notes": 434,
    "hard_notes": 260,
    "main_unit": "Î¼'s",
    "master_notes": null,
    "name": "åãã¯ä»ã®ãªãã§",
    "normal_notes": 178,
    "romaji_name": "Bokura wa Ima no Naka de",
    "time": 122,
    "translated_name": "Were All Living This Moment"
  },
  {
    "attribute": "Cool",
    "easy_notes": 119,
    "expert_notes": 476,
    "hard_notes": 280,
    "main_unit": "Î¼'s",
    "master_notes": null,
    "name": "WILD STARS",
    "normal_notes": 181,
    "romaji_name": null,
    "time": 126,
    "translated_name": null
  },
  {
    "attribute": "Pure",
    "easy_notes": 113,
    "expert_notes": 491,
    "hard_notes": 277,
    "main_unit": "Î¼'s",
    "master_notes": null,
    "name": "ãã£ã¨éæ¥ãèããã",
    "normal_notes": 172,
    "romaji_name": "Kitto Seishun ga Kikoeru",
    "time": 114,
    "translated_name": "Youll Hear Our Youth"
  },
  {
    "attribute": "Cool",
    "easy_notes": 110,
    "expert_notes": 421,
    "hard_notes": 280,
    "main_unit": "Î¼'s",
    "master_notes": null,
    "name": "è¼å¤ã®åã§è¸ããã",
    "normal_notes": 178,
    "romaji_name": "Kaguya no Shiro de Odoritai",
    "time": 126,
    "translated_name": "I Want to Dance in Kaguyas Castle"
  },
  {
    "attribute": "Smile",
    "easy_notes": 112,
    "expert_notes": 474,
    "hard_notes": 279,
    "main_unit": "Î¼'s",
    "master_notes": null,
    "name": "ã¹ã¹ã¡âãã¥ã¢ã­ã¦",
    "normal_notes": 176,
    "romaji_name": "SusumeâTomorrow",
    "time": 128,
    "translated_name": "AdvanceâTomorrow"
  },
  {
    "attribute": "Cool",
    "easy_notes": 124,
    "expert_notes": 457,
    "hard_notes": 300,
    "main_unit": "Î¼'s",
    "master_notes": null,
    "name": "No brand girls",
    "normal_notes": 186,
    "romaji_name": null,
    "time": 106,
    "translated_name": null
  },
  {
    "attribute": "Pure",
    "easy_notes": 115,
    "expert_notes": 490,
    "hard_notes": 300,
    "main_unit": "Î¼'s",
    "master_notes": null,
    "name": "Wonder zone",
    "normal_notes": 179,
    "romaji_name": null,
    "time": 122,
    "translated_name": null
  },
  {
    "attribute": "Smile",
    "easy_notes": 98,
    "expert_notes": 439,
    "hard_notes": 266,
    "main_unit": "Î¼'s",
    "master_notes": null,
    "name": "ã©ãããã«ã¹",
    "normal_notes": 167,
    "romaji_name": "Love Novels",
    "time": 107,
    "translated_name": "Love Novels"
  },
  {
    "attribute": "Smile",
    "easy_notes": 133,
    "expert_notes": 487,
    "hard_notes": 316,
    "main_unit": "Î¼'s",
    "master_notes": null,
    "name": "ããããã®Someday",
    "normal_notes": 187,
    "romaji_name": "Kore kara no Someday",
    "time": 106,
    "translated_name": "Someday in the Future"
  },
  {
    "attribute": "Cool",
    "easy_notes": 114,
    "expert_notes": 438,
    "hard_notes": 279,
    "main_unit": "Î¼'s",
    "master_notes": null,
    "name": "ç¥ããªãLove*æãã¦Love",
    "normal_notes": 177,
    "romaji_name": "Shiranai Love * Oshiete Love",
    "time": 126,
    "translated_name": "I Dont Know Love * Teach Me Love"
  },
  {
    "attribute": "Smile",
    "easy_notes": 137,
    "expert_notes": 495,
    "hard_notes": 353,
    "main_unit": "Î¼'s",
    "master_notes": null,
    "name": "START:DASH!!",
    "normal_notes": 202,
    "romaji_name": null,
    "time": 119,
    "translated_name": null
  },
  {
    "attribute": "Pure",
    "easy_notes": 119,
    "expert_notes": 471,
    "hard_notes": 265,
    "main_unit": "Î¼'s",
    "master_notes": null,
    "name": "sweet&sweet holiday",
    "normal_notes": 174,
    "romaji_name": null,
    "time": 124,
    "translated_name": null
  },
  {
    "attribute": "Smile",
    "easy_notes": 109,
    "expert_notes": 383,
    "hard_notes": 276,
    "main_unit": "Î¼'s",
    "master_notes": null,
    "name": "æã¯å¤ªé½ãããªã?",
    "normal_notes": 162,
    "romaji_name": "Ai wa Taiyou Janai?",
    "time": 98,
    "translated_name": "Isnt Love the Sun?"
  },
  {
    "attribute": "Cool",
    "easy_notes": 97,
    "expert_notes": 410,
    "hard_notes": 261,
    "main_unit": "Î¼'s",
    "master_notes": null,
    "name": "ãã¤ã¤ã¢ã³ãããªã³ã»ã¹ã®æé¬±",
    "normal_notes": 154,
    "romaji_name": "Diamond Princess no Yuuutsu",
    "time": 100,
    "translated_name": "The Diamond Princesss Melancholy"
  },
  {
    "attribute": "Smile",
    "easy_notes": 111,
    "expert_notes": 498,
    "hard_notes": 283,
    "main_unit": "Î¼'s",
    "master_notes": null,
    "name": "Love marginal",
    "normal_notes": 163,
    "romaji_name": null,
    "time": 118,
    "translated_name": null
  },
  {
    "attribute": "Pure",
    "easy_notes": 142,
    "expert_notes": 499,
    "hard_notes": 383,
    "main_unit": "Î¼'s",
    "master_notes": null,
    "name": "ã¿ã«ã©ã¢ããº",
    "normal_notes": 213,
    "romaji_name": "Takaramonos",
    "time": 114,
    "translated_name": "Treasures"
  },
  {
    "attribute": "Cool",
    "easy_notes": 125,
    "expert_notes": 509,
    "hard_notes": 321,
    "main_unit": "Î¼'s",
    "master_notes": null,
    "name": "Paradise Live",
    "normal_notes": 209,
    "romaji_name": null,
    "time": 126,
    "translated_name": null
  },
  {
    "attribute": "Pure",
    "easy_notes": 131,
    "expert_notes": 473,
    "hard_notes": 343,
    "main_unit": "Î¼'s",
    "master_notes": null,
    "name": "Listen to my heart!!",
    "normal_notes": 215,
    "romaji_name": null,
    "time": 125,
    "translated_name": null
  },
  {
    "attribute": "Smile",
    "easy_notes": 141,
    "expert_notes": 551,
    "hard_notes": 325,
    "main_unit": "Î¼'s",
    "master_notes": null,
    "name": "Music S.T.A.R.T!!",
    "normal_notes": 216,
    "romaji_name": null,
    "time": 124,
    "translated_name": null
  },
  {
    "attribute": "Cool",
    "easy_notes": 135,
    "expert_notes": 431,
    "hard_notes": 296,
    "main_unit": "Î¼'s",
    "master_notes": null,
    "name": "ãã»ã®ã»ã­ã»ãã»ãã»ã°ã»ã!",
    "normal_notes": 202,
    "romaji_name": "Aã»Noã»Neã»Gaã»Nã»Baã»Re!",
    "time": 109,
    "translated_name": "Hey, Do Your Best!"
  },
  {
    "attribute": "Cool",
    "easy_notes": 128,
    "expert_notes": 550,
    "hard_notes": 355,
    "main_unit": "Î¼'s",
    "master_notes": null,
    "name": "LOVELESS WORLD",
    "normal_notes": 226,
    "romaji_name": null,
    "time": 126,
    "translated_name": null
  },
  {
    "attribute": "Pure",
    "easy_notes": 143,
    "expert_notes": 492,
    "hard_notes": 334,
    "main_unit": "Î¼'s",
    "master_notes": null,
    "name": "after school NAVIGATORS",
    "normal_notes": 218,
    "romaji_name": null,
    "time": 125,
    "translated_name": null
  },
  {
    "attribute": "Cool",
    "easy_notes": 142,
    "expert_notes": 515,
    "hard_notes": 389,
    "main_unit": "Î¼'s",
    "master_notes": null,
    "name": "LONELIEST BABY",
    "normal_notes": 252,
    "romaji_name": null,
    "time": 126,
    "translated_name": null
  },
  {
    "attribute": "Smile",
    "easy_notes": 146,
    "expert_notes": 509,
    "hard_notes": 339,
    "main_unit": "Î¼'s",
    "master_notes": null,
    "name": "Cutie Panther",
    "normal_notes": 207,
    "romaji_name": null,
    "time": 127,
    "translated_name": null
  },
  {
    "attribute": "Smile",
    "easy_notes": 110,
    "expert_notes": 460,
    "hard_notes": 334,
    "main_unit": "Î¼'s",
    "master_notes": null,
    "name": "ããã¯åãã¡ã®å¥è·¡",
    "normal_notes": 200,
    "romaji_name": "Sore wa Bokutachi no Kiseki",
    "time": 97,
    "translated_name": "This Is Our Miracle"
  },
  {
    "attribute": "Pure",
    "easy_notes": 129,
    "expert_notes": 469,
    "hard_notes": 316,
    "main_unit": "Î¼'s",
    "master_notes": null,
    "name": "Pure girls project",
    "normal_notes": 212,
    "romaji_name": null,
    "time": 115,
    "translated_name": null
  },
  {
    "attribute": "Pure",
    "easy_notes": 94,
    "expert_notes": 445,
    "hard_notes": 303,
    "main_unit": "Î¼'s",
    "master_notes": null,
    "name": "ã©ããªã¨ãããã£ã¨",
    "normal_notes": 173,
    "romaji_name": "Donna Toki mo Zutto",
    "time": 97,
    "translated_name": "Always, No Matter When"
  },
  {
    "attribute": "Cool",
    "easy_notes": 140,
    "expert_notes": 530,
    "hard_notes": 358,
    "main_unit": "Î¼'s",
    "master_notes": null,
    "name": "å¾®ç±ããMystery",
    "normal_notes": 196,
    "romaji_name": "Binetsu kara Mystery",
    "time": 125,
    "translated_name": "A Mysterious Fever"
  },
  {
    "attribute": "Pure",
    "easy_notes": 143,
    "expert_notes": 577,
    "hard_notes": 360,
    "main_unit": "Î¼'s",
    "master_notes": null,
    "name": "ã¦ã¡ãããã©",
    "normal_notes": 227,
    "romaji_name": "Yume no Tobira",
    "time": 125,
    "translated_name": "The Door to Our Dreams"
  },
  {
    "attribute": "Smile",
    "easy_notes": 60,
    "expert_notes": 413,
    "hard_notes": 241,
    "main_unit": "Î¼'s",
    "master_notes": null,
    "name": "å¤ãçµãããªãã§ã",
    "normal_notes": 135,
    "romaji_name": "Natsu, Owaranaide.",
    "time": 111,
    "translated_name": "Summer, Dont End."
  },
  {
    "attribute": "Smile",
    "easy_notes": 91,
    "expert_notes": 438,
    "hard_notes": 291,
    "main_unit": "Î¼'s",
    "master_notes": null,
    "name": "Love wing bell",
    "normal_notes": 167,
    "romaji_name": null,
    "time": 106,
    "translated_name": null
  },
  {
    "attribute": "Cool",
    "easy_notes": 133,
    "expert_notes": 435,
    "hard_notes": 323,
    "main_unit": "Î¼'s",
    "master_notes": null,
    "name": "UNBALANCED LOVE",
    "normal_notes": 204,
    "romaji_name": null,
    "time": 126,
    "translated_name": null
  },
  {
    "attribute": "Cool",
    "easy_notes": 100,
    "expert_notes": 453,
    "hard_notes": 357,
    "main_unit": "Î¼'s",
    "master_notes": null,
    "name": "Dancing stars on me!",
    "normal_notes": 204,
    "romaji_name": null,
    "time": 112,
    "translated_name": null
  },
  {
    "attribute": "Pure",
    "easy_notes": 94,
    "expert_notes": 390,
    "hard_notes": 275,
    "main_unit": "Î¼'s",
    "master_notes": null,
    "name": "ã­ãã®ããã«!",
    "normal_notes": 149,
    "romaji_name": "Kimi no Kuse ni!",
    "time": 117,
    "translated_name": "Even Though Its You!"
  },
  {
    "attribute": "Pure",
    "easy_notes": 114,
    "expert_notes": 503,
    "hard_notes": 340,
    "main_unit": "Î¼'s",
    "master_notes": null,
    "name": "KiRa-KiRa Sensation!",
    "normal_notes": 211,
    "romaji_name": null,
    "time": 118,
    "translated_name": null
  },
  {
    "attribute": "Cool",
    "easy_notes": 73,
    "expert_notes": 358,
    "hard_notes": 201,
    "main_unit": "Î¼'s",
    "master_notes": null,
    "name": "ãããµããæ²ãã¿ã®æã¦",
    "normal_notes": 125,
    "romaji_name": "Arifureta Kanashimi no Hate",
    "time": 102,
    "translated_name": "The Reaches of My Mundane Sorrow"
  },
  {
    "attribute": "Smile",
    "easy_notes": 112,
    "expert_notes": 555,
    "hard_notes": 345,
    "main_unit": "Î¼'s",
    "master_notes": null,
    "name": "Happy maker!",
    "normal_notes": 221,
    "romaji_name": null,
    "time": 125,
    "translated_name": null
  },
  {
    "attribute": "Pure",
    "easy_notes": 130,
    "expert_notes": 541,
    "hard_notes": 394,
    "main_unit": "Î¼'s",
    "master_notes": null,
    "name": "å­¤ç¬ãªHeaven",
    "normal_notes": 248,
    "romaji_name": "Kodoku na Heaven",
    "time": 123,
    "translated_name": "A Lonely Heaven"
  },
  {
    "attribute": "Cool",
    "easy_notes": 102,
    "expert_notes": 532,
    "hard_notes": 392,
    "main_unit": "Î¼'s",
    "master_notes": null,
    "name": "ã ã£ã¦ã ã£ã¦å«ç¡æ",
    "normal_notes": 211,
    "romaji_name": "Datte Datte Aa Mujou",
    "time": 126,
    "translated_name": "Ah, but Youre so Cruel"
  },
  {
    "attribute": "Smile",
    "easy_notes": 98,
    "expert_notes": 479,
    "hard_notes": 319,
    "main_unit": "Î¼'s",
    "master_notes": null,
    "name": "Someday of my life",
    "normal_notes": 173,
    "romaji_name": null,
    "time": 115,
    "translated_name": null
  },
  {
    "attribute": "Smile",
    "easy_notes": 147,
    "expert_notes": 564,
    "hard_notes": 382,
    "main_unit": "Î¼'s",
    "master_notes": null,
    "name": "COLORFUL VOICE",
    "normal_notes": 252,
    "romaji_name": null,
    "time": 123,
    "translated_name": null
  },
  {
    "attribute": "Pure",
    "easy_notes": 94,
    "expert_notes": 414,
    "hard_notes": 299,
    "main_unit": "Î¼'s",
    "master_notes": null,
    "name": "ã¶ã~ã¹ããâ¡ã¨ããã",
    "normal_notes": 183,
    "romaji_name": "Blueberry Train",
    "time": 106,
    "translated_name": "Blueberry Train"
  },
  {
    "attribute": "Pure",
    "easy_notes": 77,
    "expert_notes": 370,
    "hard_notes": 283,
    "main_unit": "Î¼'s",
    "master_notes": null,
    "name": "SENTIMENTAL StepS",
    "normal_notes": 149,
    "romaji_name": null,
    "time": 125,
    "translated_name": null
  },
  {
    "attribute": "Cool",
    "easy_notes": 95,
    "expert_notes": 467,
    "hard_notes": 342,
    "main_unit": "Î¼'s",
    "master_notes": null,
    "name": "Daring!!",
    "normal_notes": 189,
    "romaji_name": null,
    "time": 100,
    "translated_name": null
  },
  {
    "attribute": "Smile",
    "easy_notes": 75,
    "expert_notes": 297,
    "hard_notes": 213,
    "main_unit": "Î¼'s",
    "master_notes": null,
    "name": "ããã²ã¨ããããªãã",
    "normal_notes": 136,
    "romaji_name": "Mou Hitori Janai yo",
    "time": 124,
    "translated_name": "Im Not Alone Anymore"
  },
  {
    "attribute": "Cool",
    "easy_notes": 115,
    "expert_notes": 473,
    "hard_notes": 372,
    "main_unit": "Î¼'s",
    "master_notes": null,
    "name": "åæ°ã®Reason",
    "normal_notes": 230,
    "romaji_name": "Yuuki no Reason",
    "time": 102,
    "translated_name": "The Reason for My Courage"
  },
  {
    "attribute": "Cool",
    "easy_notes": 145,
    "expert_notes": 559,
    "hard_notes": 387,
    "main_unit": "Î¼'s",
    "master_notes": null,
    "name": "ç§ãã¡ã¯æªæ¥ã®è±",
    "normal_notes": 219,
    "romaji_name": "Watashitachi wa Mirai no Hana",
    "time": 126,
    "translated_name": "We Are the Flowers of the Future"
  },
  {
    "attribute": "Smile",
    "easy_notes": 108,
    "expert_notes": 521,
    "hard_notes": 386,
    "main_unit": "Î¼'s",
    "master_notes": null,
    "name": "æã®ã·ã°ãã«Rin rin rin!",
    "normal_notes": 215,
    "romaji_name": "Koi no Signal Rin rin rin!",
    "time": 125,
    "translated_name": "Signal of Love Rin rin rin!"
  },
  {
    "attribute": "Pure",
    "easy_notes": 101,
    "expert_notes": 544,
    "hard_notes": 328,
    "main_unit": "Î¼'s",
    "master_notes": null,
    "name": "ã¹ãã«ããªãã«",
    "normal_notes": 190,
    "romaji_name": "Spicaterrible",
    "time": 123,
    "translated_name": "Spicaterrible"
  },
  {
    "attribute": "Smile",
    "easy_notes": 110,
    "expert_notes": 428,
    "hard_notes": 312,
    "main_unit": "Î¼'s",
    "master_notes": null,
    "name": "ã¾ã»ãã¤ããã¯ããã¾ãã!",
    "normal_notes": 197,
    "romaji_name": "Mahoutsukai Hajimemashita!",
    "time": 111,
    "translated_name": "I Became a Magician!"
  },
  {
    "attribute": "Pure",
    "easy_notes": 139,
    "expert_notes": 550,
    "hard_notes": 394,
    "main_unit": "Î¼'s",
    "master_notes": null,
    "name": "ç´æã¬ã³ãº",
    "normal_notes": 213,
    "romaji_name": "Junai Lens",
    "time": 125,
    "translated_name": "Pure Love Lens"
  },
  {
    "attribute": "Smile",
    "easy_notes": 125,
    "expert_notes": 577,
    "hard_notes": 362,
    "main_unit": "Î¼'s",
    "master_notes": null,
    "name": "Angelic Angel",
    "normal_notes": 207,
    "romaji_name": null,
    "time": 128,
    "translated_name": null
  },
  {
    "attribute": "Cool",
    "easy_notes": 100,
    "expert_notes": 377,
    "hard_notes": 255,
    "main_unit": "Î¼'s",
    "master_notes": null,
    "name": "Private Wars",
    "normal_notes": 146,
    "romaji_name": null,
    "time": 90,
    "translated_name": null
  },
  {
    "attribute": "Pure",
    "easy_notes": 72,
    "expert_notes": 492,
    "hard_notes": 271,
    "main_unit": "Î¼'s",
    "master_notes": null,
    "name": "ãµãããããã¹",
    "normal_notes": 152,
    "romaji_name": "Futari Happiness",
    "time": 126,
    "translated_name": "Our Happiness"
  },
  {
    "attribute": "Pure",
    "easy_notes": 119,
    "expert_notes": 566,
    "hard_notes": 390,
    "main_unit": "Î¼'s",
    "master_notes": null,
    "name": "SUNNY DAY SONG",
    "normal_notes": 221,
    "romaji_name": null,
    "time": 123,
    "translated_name": null
  },
  {
    "attribute": "Smile",
    "easy_notes": 117,
    "expert_notes": 579,
    "hard_notes": 399,
    "main_unit": "Î¼'s",
    "master_notes": null,
    "name": "Trouble Busters",
    "normal_notes": 200,
    "romaji_name": null,
    "time": 118,
    "translated_name": null
  },
  {
    "attribute": "Smile",
    "easy_notes": 118,
    "expert_notes": 494,
    "hard_notes": 375,
    "main_unit": "Î¼'s",
    "master_notes": null,
    "name": "åãã¡ã¯ã²ã¨ã¤ã®å",
    "normal_notes": 208,
    "romaji_name": "Bokutachi wa Hitotsu no Hikari",
    "time": 120,
    "translated_name": "We Are One Light"
  },
  {
    "attribute": "Cool",
    "easy_notes": 94,
    "expert_notes": 375,
    "hard_notes": 269,
    "main_unit": "Î¼'s",
    "master_notes": null,
    "name": "å°å¤å¼é³¥æè©©",
    "normal_notes": 144,
    "romaji_name": "Nightingale Love Song",
    "time": 126,
    "translated_name": "Nightingale Love Song"
  },
  {
    "attribute": "Smile",
    "easy_notes": 95,
    "expert_notes": 434,
    "hard_notes": 298,
    "main_unit": "Î¼'s",
    "master_notes": null,
    "name": "ã·ã¢ã¯ã»è¡ãã®SMILING!",
    "normal_notes": 173,
    "romaji_name": "Shiawase-iki no SMILING!",
    "time": 99,
    "translated_name": "SMILING Toward Happiness!"
  },
  {
    "attribute": "Smile",
    "easy_notes": 122,
    "expert_notes": 581,
    "hard_notes": 380,
    "main_unit": "Î¼'s",
    "master_notes": null,
    "name": "HEART to HEART!",
    "normal_notes": 233,
    "romaji_name": null,
    "time": 121,
    "translated_name": null
  },
  {
    "attribute": "Cool",
    "easy_notes": 98,
    "expert_notes": 533,
    "hard_notes": 385,
    "main_unit": "Î¼'s",
    "master_notes": null,
    "name": "åµã®ãªãã®æã ãã",
    "normal_notes": 191,
    "romaji_name": "Arashi no Naka no Koi Dakara",
    "time": 126,
    "translated_name": "Because Its a Stormy Love"
  },
  {
    "attribute": "Pure",
    "easy_notes": 58,
    "expert_notes": 310,
    "hard_notes": 230,
    "main_unit": "Î¼'s",
    "master_notes": null,
    "name": "ããããããã£ã¨",
    "normal_notes": 101,
    "romaji_name": "Moshimo kara Kitto",
    "time": 114,
    "translated_name": "From If to Definitely"
  },
  {
    "attribute": "Cool",
    "easy_notes": 77,
    "expert_notes": 324,
    "hard_notes": 231,
    "main_unit": "Î¼'s",
    "master_notes": null,
    "name": "Shocking Party",
    "normal_notes": 160,
    "romaji_name": null,
    "time": 79,
    "translated_name": null
  },
  {
    "attribute": "Pure",
    "easy_notes": 120,
    "expert_notes": 596,
    "hard_notes": 386,
    "main_unit": "Î¼'s",
    "master_notes": null,
    "name": "å¥½ãã§ããå¥½ãã§ãã?",
    "normal_notes": 220,
    "romaji_name": "Suki Desu ga Suki Desu ka?",
    "time": 121,
    "translated_name": "I Love You, but Do You Love Me?"
  },
  {
    "attribute": "Pure",
    "easy_notes": 102,
    "expert_notes": 512,
    "hard_notes": 313,
    "main_unit": "Î¼'s",
    "master_notes": null,
    "name": "ãã¯Î¼'sicã®ã",
    "normal_notes": 201,
    "romaji_name": "Mi wa Î¼sic no Mi",
    "time": 117,
    "translated_name": "M Is for Î¼sic"
  },
  {
    "attribute": "Cool",
    "easy_notes": 90,
    "expert_notes": 537,
    "hard_notes": 373,
    "main_unit": "Î¼'s",
    "master_notes": null,
    "name": "ããããMagnetic today",
    "normal_notes": 179,
    "romaji_name": "Zurui yo Magnetic today",
    "time": 115,
    "translated_name": "Unfair Magnetic today"
  },
  {
    "attribute": "Cool",
    "easy_notes": 125,
    "expert_notes": 599,
    "hard_notes": 400,
    "main_unit": "Î¼'s",
    "master_notes": null,
    "name": "Super LOVE=Super LIVE!",
    "normal_notes": 249,
    "romaji_name": null,
    "time": 128,
    "translated_name": null
  },
  {
    "attribute": "Smile",
    "easy_notes": 94,
    "expert_notes": 504,
    "hard_notes": 346,
    "main_unit": "Î¼'s",
    "master_notes": null,
    "name": "ããããMIRACLE",
    "normal_notes": 181,
    "romaji_name": "Kururin MIRACLE",
    "time": 126,
    "translated_name": "Twirling MIRACLE"
  },
  {
    "attribute": "Smile",
    "easy_notes": 124,
    "expert_notes": 584,
    "hard_notes": 411,
    "main_unit": "Î¼'s",
    "master_notes": null,
    "name": "MOMENT RING",
    "normal_notes": 232,
    "romaji_name": null,
    "time": 127,
    "translated_name": null
  },
  {
    "attribute": "Cool",
    "easy_notes": 108,
    "expert_notes": 494,
    "hard_notes": 312,
    "main_unit": "Î¼'s",
    "master_notes": null,
    "name": "Storm in Lover",
    "normal_notes": 178,
    "romaji_name": null,
    "time": 120,
    "translated_name": null
  },
  {
    "attribute": "Pure",
    "easy_notes": 95,
    "expert_notes": 452,
    "hard_notes": 344,
    "main_unit": "Î¼'s",
    "master_notes": null,
    "name": "ããããªãã¸ãããªã!",
    "normal_notes": 167,
    "romaji_name": "Sayounara he Sayonara!",
    "time": 118,
    "translated_name": "Goodbye to Goodbyes!"
  },
  {
    "attribute": "Cool",
    "easy_notes": 96,
    "expert_notes": 581,
    "hard_notes": 403,
    "main_unit": "Î¼'s",
    "master_notes": null,
    "name": "NO EXIT ORION",
    "normal_notes": 215,
    "romaji_name": null,
    "time": 125,
    "translated_name": null
  },
  {
    "attribute": "Cool",
    "easy_notes": 109,
    "expert_notes": 459,
    "hard_notes": 344,
    "main_unit": "Î¼'s",
    "master_notes": null,
    "name": "Shangri-La Shower",
    "normal_notes": 217,
    "romaji_name": "",
    "time": 128,
    "translated_name": null
  },
  {
    "attribute": "Pure",
    "easy_notes": 108,
    "expert_notes": 513,
    "hard_notes": 367,
    "main_unit": "Î¼'s",
    "master_notes": null,
    "name": "æ¥æã­ãã³ãã£ãã¯",
    "normal_notes": 171,
    "romaji_name": "Shunjou Romantic",
    "time": 118,
    "translated_name": "Passionate Romantic"
  },
  {
    "attribute": "Pure",
    "easy_notes": 111,
    "expert_notes": 569,
    "hard_notes": 353,
    "main_unit": "Î¼'s",
    "master_notes": null,
    "name": "ãã¦ãã­ã¹ã­ãã¦ã",
    "normal_notes": 208,
    "romaji_name": "Ruteshi Kisuki Shiteru",
    "time": 127,
    "translated_name": "Ouy Evol I Love You"
  },
  {
    "attribute": "Smile",
    "easy_notes": 121,
    "expert_notes": 584,
    "hard_notes": 428,
    "main_unit": "Î¼'s",
    "master_notes": null,
    "name": "PSYCHIC FIRE",
    "normal_notes": 237,
    "romaji_name": null,
    "time": 120,
    "translated_name": null
  },
  {
    "attribute": "Pure",
    "easy_notes": 109,
    "expert_notes": 515,
    "hard_notes": 348,
    "main_unit": "Î¼'s",
    "master_notes": null,
    "name": "ããã¦æå¾ã®ãã¼ã¸ã«ã¯",
    "normal_notes": 205,
    "romaji_name": "Soshite Saigo no Page ni wa",
    "time": 123,
    "translated_name": "And on the Last Page"
  },
  {
    "attribute": "Smile",
    "easy_notes": 97,
    "expert_notes": 537,
    "hard_notes": 381,
    "main_unit": "Î¼'s",
    "master_notes": null,
    "name": "ã·ãã·ãã¼ã!",
    "normal_notes": 203,
    "romaji_name": "Puwa Puwa-O!",
    "time": 122,
    "translated_name": null
  },
  {
    "attribute": "Smile",
    "easy_notes": 156,
    "expert_notes": 584,
    "hard_notes": 382,
    "main_unit": "Î¼'s",
    "master_notes": null,
    "name": "Mermaid festa vol.2 ~Passionate~",
    "normal_notes": 261,
    "romaji_name": null,
    "time": 122,
    "translated_name": null
  },
  {
    "attribute": "Pure",
    "easy_notes": 156,
    "expert_notes": 553,
    "hard_notes": 325,
    "main_unit": "Î¼'s",
    "master_notes": null,
    "name": "ä¹å¥³å¼ããããå¡¾",
    "normal_notes": 248,
    "romaji_name": "Otome Shiki Renai Juku",
    "time": 107,
    "translated_name": "Maidenly Love Cram School"
  },
  {
    "attribute": "Cool",
    "easy_notes": 153,
    "expert_notes": 563,
    "hard_notes": 351,
    "main_unit": "Î¼'s",
    "master_notes": null,
    "name": "soldier game",
    "normal_notes": 246,
    "romaji_name": null,
    "time": 102,
    "translated_name": null
  },
  {
    "attribute": "Pure",
    "easy_notes": 156,
    "expert_notes": 579,
    "hard_notes": 355,
    "main_unit": "Î¼'s",
    "master_notes": null,
    "name": "åç½æ¥åãã§ã!",
    "normal_notes": 248,
    "romaji_name": "Kokuhaku Biyori, Desu!",
    "time": 104,
    "translated_name": "Its the Perfect Day for a Confession!"
  },
  {
    "attribute": "Smile",
    "easy_notes": 204,
    "expert_notes": 612,
    "hard_notes": 442,
    "main_unit": "Î¼'s",
    "master_notes": null,
    "name": "å¤¢ãªãå¤¢ã¯å¤¢ãããªã",
    "normal_notes": 301,
    "romaji_name": "Yume naki Yume wa Yume Janai",
    "time": 115,
    "translated_name": "A Dreamless Dream Isnt a Dream"
  },
  {
    "attribute": "Cool",
    "easy_notes": 239,
    "expert_notes": 532,
    "hard_notes": 432,
    "main_unit": "Î¼'s",
    "master_notes": null,
    "name": "Anemone heart",
    "normal_notes": 365,
    "romaji_name": null,
    "time": 108,
    "translated_name": null
  },
  {
    "attribute": "Pure",
    "easy_notes": 83,
    "expert_notes": 363,
    "hard_notes": 299,
    "main_unit": "Î¼'s",
    "master_notes": null,
    "name": "ãªãã¨ã³",
    "normal_notes": 168,
    "romaji_name": "Nawatobi",
    "time": 125,
    "translated_name": "Jumping Rope"
  },
  {
    "attribute": "Cool",
    "easy_notes": 207,
    "expert_notes": 598,
    "hard_notes": 463,
    "main_unit": "Î¼'s",
    "master_notes": null,
    "name": "Beat in Angel",
    "normal_notes": 311,
    "romaji_name": null,
    "time": 112,
    "translated_name": null
  },
  {
    "attribute": "Smile",
    "easy_notes": 231,
    "expert_notes": 650,
    "hard_notes": 468,
    "main_unit": "Î¼'s",
    "master_notes": null,
    "name": "ã«ãã·ãâ¡å¥³å­é",
    "normal_notes": 320,
    "romaji_name": "Nicopuri â¡ Joshidou",
    "time": 125,
    "translated_name": "Pretty Nicos â¡ Girly Ways"
  },
  {
    "attribute": "Pure",
    "easy_notes": 186,
    "expert_notes": 609,
    "hard_notes": 489,
    "main_unit": "Î¼'s",
    "master_notes": null,
    "name": "ç¡å­ã®è±å",
    "normal_notes": 303,
    "romaji_name": "Glass no Hanazono",
    "time": 120,
    "translated_name": "Garden of Glass"
  },
  {
    "attribute": "Pure",
    "easy_notes": 112,
    "expert_notes": null,
    "hard_notes": 359,
    "main_unit": "Î¼'s",
    "master_notes": null,
    "name": "åã®ãããã¯è¼ãã¦ãããã?",
    "normal_notes": 201,
    "romaji_name": "Kimi no kokoro wa kagayaite iru kai?",
    "time": 120,
    "translated_name": "Are our hearts shining?"
  },
  {
    "attribute": "Smile",
    "easy_notes": 121,
    "expert_notes": 592,
    "hard_notes": 451,
    "main_unit": "Î¼'s",
    "master_notes": null,
    "name": "WAO-WAO Powerful day!",
    "normal_notes": 222,
    "romaji_name": null,
    "time": 122,
    "translated_name": null
  },
  {
    "attribute": "Cool",
    "easy_notes": 116,
    "expert_notes": 447,
    "hard_notes": 350,
    "main_unit": "Aqours",
    "master_notes": null,
    "name": "ãã¤ã¹ã­ã ã£ãããã¤ã¸ã§ã¦ã!",
    "normal_notes": 198,
    "romaji_name": "Daisuki dattara Daijoubu!",
    "time": 102,
    "translated_name": "If You Love It, Itll Be Fine!"
  },
  {
    "attribute": "Cool",
    "easy_notes": 99,
    "expert_notes": 429,
    "hard_notes": 317,
    "main_unit": "Î¼'s",
    "master_notes": null,
    "name": "å¬ããããäºæ",
    "normal_notes": 181,
    "romaji_name": "Fuyu ga Kureta Yokan",
    "time": 127,
    "translated_name": "The Premonition that Winter Gave Me"
  },
  {
    "attribute": "Pure",
    "easy_notes": 85,
    "expert_notes": 415,
    "hard_notes": 283,
    "main_unit": "Aqours",
    "master_notes": null,
    "name": "å¤ç©ºã¯ãªãã§ãç¥ã£ã¦ãã®?",
    "normal_notes": 174,
    "romaji_name": "Yozora wa Nandemo Shitteru no?",
    "time": 125,
    "translated_name": "Does the Night Sky Know Everything?"
  },
  {
    "attribute": "Pure",
    "easy_notes": 70,
    "expert_notes": 306,
    "hard_notes": 217,
    "main_unit": "Î¼'s",
    "master_notes": null,
    "name": "æãåºä»¥ä¸ã«ãªãããã¦",
    "normal_notes": 106,
    "romaji_name": "Omoide Ijou ni Naritakute",
    "time": 108,
    "translated_name": "I Want It to Be More than a Memory"
  },
  {
    "attribute": "Smile",
    "easy_notes": 50,
    "expert_notes": null,
    "hard_notes": 200,
    "main_unit": "Î¼'s",
    "master_notes": null,
    "name": "æãã¦ãã°ããã¼ã! (Piano Mix)",
    "normal_notes": 100,
    "romaji_name": "Aishiteru Banzai! (Piano mix)",
    "time": 101,
    "translated_name": "I Love You, Hooray! (Piano mix)"
  },
  {
    "attribute": "Smile",
    "easy_notes": 129,
    "expert_notes": 532,
    "hard_notes": 390,
    "main_unit": "Î¼'s",
    "master_notes": null,
    "name": "æ°¸é ãã¬ã³ãº",
    "normal_notes": 212,
    "romaji_name": "Eien Friends",
    "time": 128,
    "translated_name": "Forever Friends"
  },
  {
    "attribute": "Smile",
    "easy_notes": 128,
    "expert_notes": 569,
    "hard_notes": 405,
    "main_unit": "Aqours",
    "master_notes": null,
    "name": "æ±ºãããHand in Hand",
    "normal_notes": 225,
    "romaji_name": "Kimeta yo Hand in Hand",
    "time": 109,
    "translated_name": "Weve Decided Hand in Hand"
  },
  {
    "attribute": "Pure",
    "easy_notes": 94,
    "expert_notes": 458,
    "hard_notes": 336,
    "main_unit": "Î¼'s",
    "master_notes": null,
    "name": "ç§ã®ããªãã®ç©ºé ã",
    "normal_notes": 189,
    "romaji_name": "Aki no Anata no Sora Tooku",
    "time": 99,
    "translated_name": "The Distant Autumn Sky with You"
  },
  {
    "attribute": "Cool",
    "easy_notes": 85,
    "expert_notes": 500,
    "hard_notes": 302,
    "main_unit": "Î¼'s",
    "master_notes": null,
    "name": "é¯è¦CROSSROADS",
    "normal_notes": 154,
    "romaji_name": "Sakkaku CROSSROADS",
    "time": 128,
    "translated_name": "Delusion CROSSROADS"
  }
]

);app.constant('SongTitles',
[
  {
    "attribute": "Smile",
    "easy_notes": 101,
    "expert_notes": 515,
    "hard_notes": 330,
    "main_unit": "Aqours",
    "master_notes": null,
    "name": "AqoursâHEROES",
    "normal_notes": 207,
    "romaji_name": null,
    "time": 115,
    "translated_name": null
  },
  {
    "attribute": "Cool",
    "easy_notes": 106,
    "expert_notes": 584,
    "hard_notes": 390,
    "main_unit": "Aqours",
    "master_notes": null,
    "name": "Step! ZERO to ONE",
    "normal_notes": 218,
    "romaji_name": null,
    "time": 119,
    "translated_name": null
  },
  {
    "attribute": "Cool",
    "easy_notes": 102,
    "expert_notes": 535,
    "hard_notes": 360,
    "main_unit": "Aqours",
    "master_notes": null,
    "name": "Strawberry Trapper",
    "normal_notes": 175,
    "romaji_name": null,
    "time": 101,
    "translated_name": null
  },
  {
    "attribute": "Cool",
    "easy_notes": 81,
    "expert_notes": 371,
    "hard_notes": 259,
    "main_unit": "Aqours",
    "master_notes": null,
    "name": "ã¨ãããåé¡å­¦",
    "normal_notes": 146,
    "romaji_name": "Tokimeki Bunruigaku",
    "time": 123,
    "translated_name": "The Taxonomy of Excitement"
  },
  {
    "attribute": "Pure",
    "easy_notes": 100,
    "expert_notes": 478,
    "hard_notes": 331,
    "main_unit": "Aqours",
    "master_notes": null,
    "name": "ããªã³ãªã³PLEASE!!",
    "normal_notes": 195,
    "romaji_name": "Torikoriko PLEASE!!",
    "time": 103,
    "translated_name": "Please Let Me Capture Your Heart!!"
  },
  {
    "attribute": "Smile",
    "easy_notes": 95,
    "expert_notes": 348,
    "hard_notes": 181,
    "main_unit": "Î¼'s",
    "master_notes": 697,
    "name": "åãã®LIVE åã¨ã®LIFE",
    "normal_notes": 120,
    "romaji_name": "Bokura no LIVE Kimi to no LIFE",
    "time": 125,
    "translated_name": "Our Live, Life with You"
  },
  {
    "attribute": "Smile",
    "easy_notes": 120,
    "expert_notes": 592,
    "hard_notes": 412,
    "main_unit": "Aqours",
    "master_notes": null,
    "name": "åæ°å¨éDAY!DAY!DAY!",
    "normal_notes": 228,
    "romaji_name": "Genki Zenkai DAY! DAY! DAY!",
    "time": 126,
    "translated_name": "Full Throttle Energy DAY! DAY! DAY!"
  },
  {
    "attribute": "Pure",
    "easy_notes": 112,
    "expert_notes": 497,
    "hard_notes": 359,
    "main_unit": "Aqours",
    "master_notes": null,
    "name": "åã®ãããã¯è¼ãã¦ããã?",
    "normal_notes": 201,
    "romaji_name": "Kimi no Kokoro wa Kagayaiteru kai?",
    "time": 120,
    "translated_name": "Is Your Heart Shining?"
  },
  {
    "attribute": "Smile",
    "easy_notes": 122,
    "expert_notes": 563,
    "hard_notes": 407,
    "main_unit": "Aqours",
    "master_notes": null,
    "name": "å±ããªãæã ã¨ãã¦ã",
    "normal_notes": 224,
    "romaji_name": "Todokanai Hoshi da to Shitemo",
    "time": 126,
    "translated_name": "Even if Its an Unreachable Star"
  },
  {
    "attribute": "Pure",
    "easy_notes": 95,
    "expert_notes": 466,
    "hard_notes": 334,
    "main_unit": "Aqours",
    "master_notes": null,
    "name": "å¾ã£ã¦ã¦æã®ãã",
    "normal_notes": 164,
    "romaji_name": "Mattete Ai no Uta",
    "time": 125,
    "translated_name": "Wait for Me: A Love Song"
  },
  {
    "attribute": "Cool",
    "easy_notes": 108,
    "expert_notes": 544,
    "hard_notes": 379,
    "main_unit": "Aqours",
    "master_notes": null,
    "name": "æã«ãªãããAQUARIUM",
    "normal_notes": 184,
    "romaji_name": "Koi ni Naritai AQUARIUM",
    "time": 123,
    "translated_name": "I Want Love to Bloom at the Aquarium"
  },
  {
    "attribute": "Pure",
    "easy_notes": 91,
    "expert_notes": 359,
    "hard_notes": 204,
    "main_unit": "Î¼'s",
    "master_notes": 640,
    "name": "åæãã¼ãã§ã³ã¸",
    "normal_notes": 125,
    "romaji_name": "Yuujou No Change",
    "time": 124,
    "translated_name": "Unchanging Friendship"
  },
  {
    "attribute": "Pure",
    "easy_notes": 97,
    "expert_notes": 362,
    "hard_notes": 220,
    "main_unit": "Î¼'s",
    "master_notes": null,
    "name": "baby maybe æã®ãã¿ã³",
    "normal_notes": 148,
    "romaji_name": "baby maybe Koi no Button",
    "time": 125,
    "translated_name": "baby maybe Button of Love"
  },
  {
    "attribute": "Cool",
    "easy_notes": 81,
    "expert_notes": 355,
    "hard_notes": 206,
    "main_unit": "Î¼'s",
    "master_notes": 551,
    "name": "Snow halation",
    "normal_notes": 139,
    "romaji_name": null,
    "time": 123,
    "translated_name": null
  },
  {
    "attribute": "Smile",
    "easy_notes": 105,
    "expert_notes": 471,
    "hard_notes": 360,
    "main_unit": "Aqours",
    "master_notes": null,
    "name": "éç©ºJumping Heart",
    "normal_notes": 208,
    "romaji_name": "Aozora Jumping Heart",
    "time": 97,
    "translated_name": "Blue Sky Jumping Heart"
  },
  {
    "attribute": "Pure",
    "easy_notes": 106,
    "expert_notes": 471,
    "hard_notes": 329,
    "main_unit": "Aqours",
    "master_notes": null,
    "name": "ã¦ã¡èªãããã¦ã¡æ­ãã",
    "normal_notes": 187,
    "romaji_name": "Yume Kataru yori Yume Utaou",
    "time": 106,
    "translated_name": "Sing Your Dreams Instead of Talking about Them"
  },
  {
    "attribute": "Cool",
    "easy_notes": 99,
    "expert_notes": 431,
    "hard_notes": 237,
    "main_unit": "Î¼'s",
    "master_notes": null,
    "name": "Mermaid festa vol.1",
    "normal_notes": 158,
    "romaji_name": null,
    "time": 121,
    "translated_name": null
  },
  {
    "attribute": "Smile",
    "easy_notes": 85,
    "expert_notes": 370,
    "hard_notes": 225,
    "main_unit": "Î¼'s",
    "master_notes": 786,
    "name": "å¤è²ãããã§1,2,Jump!",
    "normal_notes": 146,
    "romaji_name": "Natsu-iro Egao de 1, 2, Jump!",
    "time": 125,
    "translated_name": "1, 2, Jump with a Summer-Colored Smile!"
  },
  {
    "attribute": "Pure",
    "easy_notes": 89,
    "expert_notes": 391,
    "hard_notes": 224,
    "main_unit": "Î¼'s",
    "master_notes": 575,
    "name": "ãããã£ã¨\"love\"ã§æ¥è¿ä¸­!",
    "normal_notes": 143,
    "romaji_name": "Mogyutto love de Sekkinchuu!",
    "time": 125,
    "translated_name": "Grab Tightly When Getting Closer to Love!"
  },
  {
    "attribute": "Smile",
    "easy_notes": 90,
    "expert_notes": 302,
    "hard_notes": 223,
    "main_unit": "Î¼'s",
    "master_notes": null,
    "name": "æãã¦ãã°ããã¼ã!",
    "normal_notes": 164,
    "romaji_name": "Aishiteru Banzai!",
    "time": 112,
    "translated_name": "I Love You, Hooray!"
  },
  {
    "attribute": "Smile",
    "easy_notes": 113,
    "expert_notes": 457,
    "hard_notes": 255,
    "main_unit": "Î¼'s",
    "master_notes": null,
    "name": "Oh,Love&Peace!",
    "normal_notes": 183,
    "romaji_name": null,
    "time": 125,
    "translated_name": null
  },
  {
    "attribute": "Cool",
    "easy_notes": 111,
    "expert_notes": 386,
    "hard_notes": 247,
    "main_unit": "Î¼'s",
    "master_notes": 616,
    "name": "Wonderful Rush",
    "normal_notes": 172,
    "romaji_name": null,
    "time": 113,
    "translated_name": null
  },
  {
    "attribute": "Smile",
    "easy_notes": 110,
    "expert_notes": 434,
    "hard_notes": 260,
    "main_unit": "Î¼'s",
    "master_notes": null,
    "name": "åãã¯ä»ã®ãªãã§",
    "normal_notes": 178,
    "romaji_name": "Bokura wa Ima no Naka de",
    "time": 122,
    "translated_name": "Were All Living This Moment"
  },
  {
    "attribute": "Cool",
    "easy_notes": 119,
    "expert_notes": 476,
    "hard_notes": 280,
    "main_unit": "Î¼'s",
    "master_notes": null,
    "name": "WILD STARS",
    "normal_notes": 181,
    "romaji_name": null,
    "time": 126,
    "translated_name": null
  },
  {
    "attribute": "Pure",
    "easy_notes": 113,
    "expert_notes": 491,
    "hard_notes": 277,
    "main_unit": "Î¼'s",
    "master_notes": null,
    "name": "ãã£ã¨éæ¥ãèããã",
    "normal_notes": 172,
    "romaji_name": "Kitto Seishun ga Kikoeru",
    "time": 114,
    "translated_name": "Youll Hear Our Youth"
  },
  {
    "attribute": "Cool",
    "easy_notes": 110,
    "expert_notes": 421,
    "hard_notes": 280,
    "main_unit": "Î¼'s",
    "master_notes": null,
    "name": "è¼å¤ã®åã§è¸ããã",
    "normal_notes": 178,
    "romaji_name": "Kaguya no Shiro de Odoritai",
    "time": 126,
    "translated_name": "I Want to Dance in Kaguyas Castle"
  },
  {
    "attribute": "Smile",
    "easy_notes": 112,
    "expert_notes": 474,
    "hard_notes": 279,
    "main_unit": "Î¼'s",
    "master_notes": null,
    "name": "ã¹ã¹ã¡âãã¥ã¢ã­ã¦",
    "normal_notes": 176,
    "romaji_name": "SusumeâTomorrow",
    "time": 128,
    "translated_name": "AdvanceâTomorrow"
  },
  {
    "attribute": "Cool",
    "easy_notes": 124,
    "expert_notes": 457,
    "hard_notes": 300,
    "main_unit": "Î¼'s",
    "master_notes": null,
    "name": "No brand girls",
    "normal_notes": 186,
    "romaji_name": null,
    "time": 106,
    "translated_name": null
  },
  {
    "attribute": "Pure",
    "easy_notes": 115,
    "expert_notes": 490,
    "hard_notes": 300,
    "main_unit": "Î¼'s",
    "master_notes": null,
    "name": "Wonder zone",
    "normal_notes": 179,
    "romaji_name": null,
    "time": 122,
    "translated_name": null
  },
  {
    "attribute": "Smile",
    "easy_notes": 98,
    "expert_notes": 439,
    "hard_notes": 266,
    "main_unit": "Î¼'s",
    "master_notes": null,
    "name": "ã©ãããã«ã¹",
    "normal_notes": 167,
    "romaji_name": "Love Novels",
    "time": 107,
    "translated_name": "Love Novels"
  },
  {
    "attribute": "Smile",
    "easy_notes": 133,
    "expert_notes": 487,
    "hard_notes": 316,
    "main_unit": "Î¼'s",
    "master_notes": null,
    "name": "ããããã®Someday",
    "normal_notes": 187,
    "romaji_name": "Kore kara no Someday",
    "time": 106,
    "translated_name": "Someday in the Future"
  },
  {
    "attribute": "Cool",
    "easy_notes": 114,
    "expert_notes": 438,
    "hard_notes": 279,
    "main_unit": "Î¼'s",
    "master_notes": null,
    "name": "ç¥ããªãLove*æãã¦Love",
    "normal_notes": 177,
    "romaji_name": "Shiranai Love * Oshiete Love",
    "time": 126,
    "translated_name": "I Dont Know Love * Teach Me Love"
  },
  {
    "attribute": "Smile",
    "easy_notes": 137,
    "expert_notes": 495,
    "hard_notes": 353,
    "main_unit": "Î¼'s",
    "master_notes": null,
    "name": "START:DASH!!",
    "normal_notes": 202,
    "romaji_name": null,
    "time": 119,
    "translated_name": null
  },
  {
    "attribute": "Pure",
    "easy_notes": 119,
    "expert_notes": 471,
    "hard_notes": 265,
    "main_unit": "Î¼'s",
    "master_notes": null,
    "name": "sweet&sweet holiday",
    "normal_notes": 174,
    "romaji_name": null,
    "time": 124,
    "translated_name": null
  },
  {
    "attribute": "Smile",
    "easy_notes": 109,
    "expert_notes": 383,
    "hard_notes": 276,
    "main_unit": "Î¼'s",
    "master_notes": null,
    "name": "æã¯å¤ªé½ãããªã?",
    "normal_notes": 162,
    "romaji_name": "Ai wa Taiyou Janai?",
    "time": 98,
    "translated_name": "Isnt Love the Sun?"
  },
  {
    "attribute": "Cool",
    "easy_notes": 97,
    "expert_notes": 410,
    "hard_notes": 261,
    "main_unit": "Î¼'s",
    "master_notes": null,
    "name": "ãã¤ã¤ã¢ã³ãããªã³ã»ã¹ã®æé¬±",
    "normal_notes": 154,
    "romaji_name": "Diamond Princess no Yuuutsu",
    "time": 100,
    "translated_name": "The Diamond Princesss Melancholy"
  },
  {
    "attribute": "Smile",
    "easy_notes": 111,
    "expert_notes": 498,
    "hard_notes": 283,
    "main_unit": "Î¼'s",
    "master_notes": null,
    "name": "Love marginal",
    "normal_notes": 163,
    "romaji_name": null,
    "time": 118,
    "translated_name": null
  },
  {
    "attribute": "Pure",
    "easy_notes": 142,
    "expert_notes": 499,
    "hard_notes": 383,
    "main_unit": "Î¼'s",
    "master_notes": null,
    "name": "ã¿ã«ã©ã¢ããº",
    "normal_notes": 213,
    "romaji_name": "Takaramonos",
    "time": 114,
    "translated_name": "Treasures"
  },
  {
    "attribute": "Cool",
    "easy_notes": 125,
    "expert_notes": 509,
    "hard_notes": 321,
    "main_unit": "Î¼'s",
    "master_notes": null,
    "name": "Paradise Live",
    "normal_notes": 209,
    "romaji_name": null,
    "time": 126,
    "translated_name": null
  },
  {
    "attribute": "Pure",
    "easy_notes": 131,
    "expert_notes": 473,
    "hard_notes": 343,
    "main_unit": "Î¼'s",
    "master_notes": null,
    "name": "Listen to my heart!!",
    "normal_notes": 215,
    "romaji_name": null,
    "time": 125,
    "translated_name": null
  },
  {
    "attribute": "Smile",
    "easy_notes": 141,
    "expert_notes": 551,
    "hard_notes": 325,
    "main_unit": "Î¼'s",
    "master_notes": null,
    "name": "Music S.T.A.R.T!!",
    "normal_notes": 216,
    "romaji_name": null,
    "time": 124,
    "translated_name": null
  },
  {
    "attribute": "Cool",
    "easy_notes": 135,
    "expert_notes": 431,
    "hard_notes": 296,
    "main_unit": "Î¼'s",
    "master_notes": null,
    "name": "ãã»ã®ã»ã­ã»ãã»ãã»ã°ã»ã!",
    "normal_notes": 202,
    "romaji_name": "Aã»Noã»Neã»Gaã»Nã»Baã»Re!",
    "time": 109,
    "translated_name": "Hey, Do Your Best!"
  },
  {
    "attribute": "Cool",
    "easy_notes": 128,
    "expert_notes": 550,
    "hard_notes": 355,
    "main_unit": "Î¼'s",
    "master_notes": null,
    "name": "LOVELESS WORLD",
    "normal_notes": 226,
    "romaji_name": null,
    "time": 126,
    "translated_name": null
  },
  {
    "attribute": "Pure",
    "easy_notes": 143,
    "expert_notes": 492,
    "hard_notes": 334,
    "main_unit": "Î¼'s",
    "master_notes": null,
    "name": "after school NAVIGATORS",
    "normal_notes": 218,
    "romaji_name": null,
    "time": 125,
    "translated_name": null
  },
  {
    "attribute": "Cool",
    "easy_notes": 142,
    "expert_notes": 515,
    "hard_notes": 389,
    "main_unit": "Î¼'s",
    "master_notes": null,
    "name": "LONELIEST BABY",
    "normal_notes": 252,
    "romaji_name": null,
    "time": 126,
    "translated_name": null
  },
  {
    "attribute": "Smile",
    "easy_notes": 146,
    "expert_notes": 509,
    "hard_notes": 339,
    "main_unit": "Î¼'s",
    "master_notes": null,
    "name": "Cutie Panther",
    "normal_notes": 207,
    "romaji_name": null,
    "time": 127,
    "translated_name": null
  },
  {
    "attribute": "Smile",
    "easy_notes": 110,
    "expert_notes": 460,
    "hard_notes": 334,
    "main_unit": "Î¼'s",
    "master_notes": null,
    "name": "ããã¯åãã¡ã®å¥è·¡",
    "normal_notes": 200,
    "romaji_name": "Sore wa Bokutachi no Kiseki",
    "time": 97,
    "translated_name": "This Is Our Miracle"
  },
  {
    "attribute": "Pure",
    "easy_notes": 129,
    "expert_notes": 469,
    "hard_notes": 316,
    "main_unit": "Î¼'s",
    "master_notes": null,
    "name": "Pure girls project",
    "normal_notes": 212,
    "romaji_name": null,
    "time": 115,
    "translated_name": null
  },
  {
    "attribute": "Pure",
    "easy_notes": 94,
    "expert_notes": 445,
    "hard_notes": 303,
    "main_unit": "Î¼'s",
    "master_notes": null,
    "name": "ã©ããªã¨ãããã£ã¨",
    "normal_notes": 173,
    "romaji_name": "Donna Toki mo Zutto",
    "time": 97,
    "translated_name": "Always, No Matter When"
  },
  {
    "attribute": "Cool",
    "easy_notes": 140,
    "expert_notes": 530,
    "hard_notes": 358,
    "main_unit": "Î¼'s",
    "master_notes": null,
    "name": "å¾®ç±ããMystery",
    "normal_notes": 196,
    "romaji_name": "Binetsu kara Mystery",
    "time": 125,
    "translated_name": "A Mysterious Fever"
  },
  {
    "attribute": "Pure",
    "easy_notes": 143,
    "expert_notes": 577,
    "hard_notes": 360,
    "main_unit": "Î¼'s",
    "master_notes": null,
    "name": "ã¦ã¡ãããã©",
    "normal_notes": 227,
    "romaji_name": "Yume no Tobira",
    "time": 125,
    "translated_name": "The Door to Our Dreams"
  },
  {
    "attribute": "Smile",
    "easy_notes": 60,
    "expert_notes": 413,
    "hard_notes": 241,
    "main_unit": "Î¼'s",
    "master_notes": null,
    "name": "å¤ãçµãããªãã§ã",
    "normal_notes": 135,
    "romaji_name": "Natsu, Owaranaide.",
    "time": 111,
    "translated_name": "Summer, Dont End."
  },
  {
    "attribute": "Smile",
    "easy_notes": 91,
    "expert_notes": 438,
    "hard_notes": 291,
    "main_unit": "Î¼'s",
    "master_notes": null,
    "name": "Love wing bell",
    "normal_notes": 167,
    "romaji_name": null,
    "time": 106,
    "translated_name": null
  },
  {
    "attribute": "Cool",
    "easy_notes": 133,
    "expert_notes": 435,
    "hard_notes": 323,
    "main_unit": "Î¼'s",
    "master_notes": null,
    "name": "UNBALANCED LOVE",
    "normal_notes": 204,
    "romaji_name": null,
    "time": 126,
    "translated_name": null
  },
  {
    "attribute": "Cool",
    "easy_notes": 100,
    "expert_notes": 453,
    "hard_notes": 357,
    "main_unit": "Î¼'s",
    "master_notes": null,
    "name": "Dancing stars on me!",
    "normal_notes": 204,
    "romaji_name": null,
    "time": 112,
    "translated_name": null
  },
  {
    "attribute": "Pure",
    "easy_notes": 94,
    "expert_notes": 390,
    "hard_notes": 275,
    "main_unit": "Î¼'s",
    "master_notes": null,
    "name": "ã­ãã®ããã«!",
    "normal_notes": 149,
    "romaji_name": "Kimi no Kuse ni!",
    "time": 117,
    "translated_name": "Even Though Its You!"
  },
  {
    "attribute": "Pure",
    "easy_notes": 114,
    "expert_notes": 503,
    "hard_notes": 340,
    "main_unit": "Î¼'s",
    "master_notes": null,
    "name": "KiRa-KiRa Sensation!",
    "normal_notes": 211,
    "romaji_name": null,
    "time": 118,
    "translated_name": null
  },
  {
    "attribute": "Cool",
    "easy_notes": 73,
    "expert_notes": 358,
    "hard_notes": 201,
    "main_unit": "Î¼'s",
    "master_notes": null,
    "name": "ãããµããæ²ãã¿ã®æã¦",
    "normal_notes": 125,
    "romaji_name": "Arifureta Kanashimi no Hate",
    "time": 102,
    "translated_name": "The Reaches of My Mundane Sorrow"
  },
  {
    "attribute": "Smile",
    "easy_notes": 112,
    "expert_notes": 555,
    "hard_notes": 345,
    "main_unit": "Î¼'s",
    "master_notes": null,
    "name": "Happy maker!",
    "normal_notes": 221,
    "romaji_name": null,
    "time": 125,
    "translated_name": null
  },
  {
    "attribute": "Pure",
    "easy_notes": 130,
    "expert_notes": 541,
    "hard_notes": 394,
    "main_unit": "Î¼'s",
    "master_notes": null,
    "name": "å­¤ç¬ãªHeaven",
    "normal_notes": 248,
    "romaji_name": "Kodoku na Heaven",
    "time": 123,
    "translated_name": "A Lonely Heaven"
  },
  {
    "attribute": "Cool",
    "easy_notes": 102,
    "expert_notes": 532,
    "hard_notes": 392,
    "main_unit": "Î¼'s",
    "master_notes": null,
    "name": "ã ã£ã¦ã ã£ã¦å«ç¡æ",
    "normal_notes": 211,
    "romaji_name": "Datte Datte Aa Mujou",
    "time": 126,
    "translated_name": "Ah, but Youre so Cruel"
  },
  {
    "attribute": "Smile",
    "easy_notes": 98,
    "expert_notes": 479,
    "hard_notes": 319,
    "main_unit": "Î¼'s",
    "master_notes": null,
    "name": "Someday of my life",
    "normal_notes": 173,
    "romaji_name": null,
    "time": 115,
    "translated_name": null
  },
  {
    "attribute": "Smile",
    "easy_notes": 147,
    "expert_notes": 564,
    "hard_notes": 382,
    "main_unit": "Î¼'s",
    "master_notes": null,
    "name": "COLORFUL VOICE",
    "normal_notes": 252,
    "romaji_name": null,
    "time": 123,
    "translated_name": null
  },
  {
    "attribute": "Pure",
    "easy_notes": 94,
    "expert_notes": 414,
    "hard_notes": 299,
    "main_unit": "Î¼'s",
    "master_notes": null,
    "name": "ã¶ã~ã¹ããâ¡ã¨ããã",
    "normal_notes": 183,
    "romaji_name": "Blueberry Train",
    "time": 106,
    "translated_name": "Blueberry Train"
  },
  {
    "attribute": "Pure",
    "easy_notes": 77,
    "expert_notes": 370,
    "hard_notes": 283,
    "main_unit": "Î¼'s",
    "master_notes": null,
    "name": "SENTIMENTAL StepS",
    "normal_notes": 149,
    "romaji_name": null,
    "time": 125,
    "translated_name": null
  },
  {
    "attribute": "Cool",
    "easy_notes": 95,
    "expert_notes": 467,
    "hard_notes": 342,
    "main_unit": "Î¼'s",
    "master_notes": null,
    "name": "Daring!!",
    "normal_notes": 189,
    "romaji_name": null,
    "time": 100,
    "translated_name": null
  },
  {
    "attribute": "Smile",
    "easy_notes": 75,
    "expert_notes": 297,
    "hard_notes": 213,
    "main_unit": "Î¼'s",
    "master_notes": null,
    "name": "ããã²ã¨ããããªãã",
    "normal_notes": 136,
    "romaji_name": "Mou Hitori Janai yo",
    "time": 124,
    "translated_name": "Im Not Alone Anymore"
  },
  {
    "attribute": "Cool",
    "easy_notes": 115,
    "expert_notes": 473,
    "hard_notes": 372,
    "main_unit": "Î¼'s",
    "master_notes": null,
    "name": "åæ°ã®Reason",
    "normal_notes": 230,
    "romaji_name": "Yuuki no Reason",
    "time": 102,
    "translated_name": "The Reason for My Courage"
  },
  {
    "attribute": "Cool",
    "easy_notes": 145,
    "expert_notes": 559,
    "hard_notes": 387,
    "main_unit": "Î¼'s",
    "master_notes": null,
    "name": "ç§ãã¡ã¯æªæ¥ã®è±",
    "normal_notes": 219,
    "romaji_name": "Watashitachi wa Mirai no Hana",
    "time": 126,
    "translated_name": "We Are the Flowers of the Future"
  },
  {
    "attribute": "Smile",
    "easy_notes": 108,
    "expert_notes": 521,
    "hard_notes": 386,
    "main_unit": "Î¼'s",
    "master_notes": null,
    "name": "æã®ã·ã°ãã«Rin rin rin!",
    "normal_notes": 215,
    "romaji_name": "Koi no Signal Rin rin rin!",
    "time": 125,
    "translated_name": "Signal of Love Rin rin rin!"
  },
  {
    "attribute": "Pure",
    "easy_notes": 101,
    "expert_notes": 544,
    "hard_notes": 328,
    "main_unit": "Î¼'s",
    "master_notes": null,
    "name": "ã¹ãã«ããªãã«",
    "normal_notes": 190,
    "romaji_name": "Spicaterrible",
    "time": 123,
    "translated_name": "Spicaterrible"
  },
  {
    "attribute": "Smile",
    "easy_notes": 110,
    "expert_notes": 428,
    "hard_notes": 312,
    "main_unit": "Î¼'s",
    "master_notes": null,
    "name": "ã¾ã»ãã¤ããã¯ããã¾ãã!",
    "normal_notes": 197,
    "romaji_name": "Mahoutsukai Hajimemashita!",
    "time": 111,
    "translated_name": "I Became a Magician!"
  },
  {
    "attribute": "Pure",
    "easy_notes": 139,
    "expert_notes": 550,
    "hard_notes": 394,
    "main_unit": "Î¼'s",
    "master_notes": null,
    "name": "ç´æã¬ã³ãº",
    "normal_notes": 213,
    "romaji_name": "Junai Lens",
    "time": 125,
    "translated_name": "Pure Love Lens"
  },
  {
    "attribute": "Smile",
    "easy_notes": 125,
    "expert_notes": 577,
    "hard_notes": 362,
    "main_unit": "Î¼'s",
    "master_notes": null,
    "name": "Angelic Angel",
    "normal_notes": 207,
    "romaji_name": null,
    "time": 128,
    "translated_name": null
  },
  {
    "attribute": "Cool",
    "easy_notes": 100,
    "expert_notes": 377,
    "hard_notes": 255,
    "main_unit": "Î¼'s",
    "master_notes": null,
    "name": "Private Wars",
    "normal_notes": 146,
    "romaji_name": null,
    "time": 90,
    "translated_name": null
  },
  {
    "attribute": "Pure",
    "easy_notes": 72,
    "expert_notes": 492,
    "hard_notes": 271,
    "main_unit": "Î¼'s",
    "master_notes": null,
    "name": "ãµãããããã¹",
    "normal_notes": 152,
    "romaji_name": "Futari Happiness",
    "time": 126,
    "translated_name": "Our Happiness"
  },
  {
    "attribute": "Pure",
    "easy_notes": 119,
    "expert_notes": 566,
    "hard_notes": 390,
    "main_unit": "Î¼'s",
    "master_notes": null,
    "name": "SUNNY DAY SONG",
    "normal_notes": 221,
    "romaji_name": null,
    "time": 123,
    "translated_name": null
  },
  {
    "attribute": "Smile",
    "easy_notes": 117,
    "expert_notes": 579,
    "hard_notes": 399,
    "main_unit": "Î¼'s",
    "master_notes": null,
    "name": "Trouble Busters",
    "normal_notes": 200,
    "romaji_name": null,
    "time": 118,
    "translated_name": null
  },
  {
    "attribute": "Smile",
    "easy_notes": 118,
    "expert_notes": 494,
    "hard_notes": 375,
    "main_unit": "Î¼'s",
    "master_notes": null,
    "name": "åãã¡ã¯ã²ã¨ã¤ã®å",
    "normal_notes": 208,
    "romaji_name": "Bokutachi wa Hitotsu no Hikari",
    "time": 120,
    "translated_name": "We Are One Light"
  },
  {
    "attribute": "Cool",
    "easy_notes": 94,
    "expert_notes": 375,
    "hard_notes": 269,
    "main_unit": "Î¼'s",
    "master_notes": null,
    "name": "å°å¤å¼é³¥æè©©",
    "normal_notes": 144,
    "romaji_name": "Nightingale Love Song",
    "time": 126,
    "translated_name": "Nightingale Love Song"
  },
  {
    "attribute": "Smile",
    "easy_notes": 95,
    "expert_notes": 434,
    "hard_notes": 298,
    "main_unit": "Î¼'s",
    "master_notes": null,
    "name": "ã·ã¢ã¯ã»è¡ãã®SMILING!",
    "normal_notes": 173,
    "romaji_name": "Shiawase-iki no SMILING!",
    "time": 99,
    "translated_name": "SMILING Toward Happiness!"
  },
  {
    "attribute": "Smile",
    "easy_notes": 122,
    "expert_notes": 581,
    "hard_notes": 380,
    "main_unit": "Î¼'s",
    "master_notes": null,
    "name": "HEART to HEART!",
    "normal_notes": 233,
    "romaji_name": null,
    "time": 121,
    "translated_name": null
  },
  {
    "attribute": "Cool",
    "easy_notes": 98,
    "expert_notes": 533,
    "hard_notes": 385,
    "main_unit": "Î¼'s",
    "master_notes": null,
    "name": "åµã®ãªãã®æã ãã",
    "normal_notes": 191,
    "romaji_name": "Arashi no Naka no Koi Dakara",
    "time": 126,
    "translated_name": "Because Its a Stormy Love"
  },
  {
    "attribute": "Pure",
    "easy_notes": 58,
    "expert_notes": 310,
    "hard_notes": 230,
    "main_unit": "Î¼'s",
    "master_notes": null,
    "name": "ããããããã£ã¨",
    "normal_notes": 101,
    "romaji_name": "Moshimo kara Kitto",
    "time": 114,
    "translated_name": "From If to Definitely"
  },
  {
    "attribute": "Cool",
    "easy_notes": 77,
    "expert_notes": 324,
    "hard_notes": 231,
    "main_unit": "Î¼'s",
    "master_notes": null,
    "name": "Shocking Party",
    "normal_notes": 160,
    "romaji_name": null,
    "time": 79,
    "translated_name": null
  },
  {
    "attribute": "Pure",
    "easy_notes": 120,
    "expert_notes": 596,
    "hard_notes": 386,
    "main_unit": "Î¼'s",
    "master_notes": null,
    "name": "å¥½ãã§ããå¥½ãã§ãã?",
    "normal_notes": 220,
    "romaji_name": "Suki Desu ga Suki Desu ka?",
    "time": 121,
    "translated_name": "I Love You, but Do You Love Me?"
  },
  {
    "attribute": "Pure",
    "easy_notes": 102,
    "expert_notes": 512,
    "hard_notes": 313,
    "main_unit": "Î¼'s",
    "master_notes": null,
    "name": "ãã¯Î¼'sicã®ã",
    "normal_notes": 201,
    "romaji_name": "Mi wa Î¼sic no Mi",
    "time": 117,
    "translated_name": "M Is for Î¼sic"
  },
  {
    "attribute": "Cool",
    "easy_notes": 90,
    "expert_notes": 537,
    "hard_notes": 373,
    "main_unit": "Î¼'s",
    "master_notes": null,
    "name": "ããããMagnetic today",
    "normal_notes": 179,
    "romaji_name": "Zurui yo Magnetic today",
    "time": 115,
    "translated_name": "Unfair Magnetic today"
  },
  {
    "attribute": "Cool",
    "easy_notes": 125,
    "expert_notes": 599,
    "hard_notes": 400,
    "main_unit": "Î¼'s",
    "master_notes": null,
    "name": "Super LOVE=Super LIVE!",
    "normal_notes": 249,
    "romaji_name": null,
    "time": 128,
    "translated_name": null
  },
  {
    "attribute": "Smile",
    "easy_notes": 94,
    "expert_notes": 504,
    "hard_notes": 346,
    "main_unit": "Î¼'s",
    "master_notes": null,
    "name": "ããããMIRACLE",
    "normal_notes": 181,
    "romaji_name": "Kururin MIRACLE",
    "time": 126,
    "translated_name": "Twirling MIRACLE"
  },
  {
    "attribute": "Smile",
    "easy_notes": 124,
    "expert_notes": 584,
    "hard_notes": 411,
    "main_unit": "Î¼'s",
    "master_notes": null,
    "name": "MOMENT RING",
    "normal_notes": 232,
    "romaji_name": null,
    "time": 127,
    "translated_name": null
  },
  {
    "attribute": "Cool",
    "easy_notes": 108,
    "expert_notes": 494,
    "hard_notes": 312,
    "main_unit": "Î¼'s",
    "master_notes": null,
    "name": "Storm in Lover",
    "normal_notes": 178,
    "romaji_name": null,
    "time": 120,
    "translated_name": null
  },
  {
    "attribute": "Pure",
    "easy_notes": 95,
    "expert_notes": 452,
    "hard_notes": 344,
    "main_unit": "Î¼'s",
    "master_notes": null,
    "name": "ããããªãã¸ãããªã!",
    "normal_notes": 167,
    "romaji_name": "Sayounara he Sayonara!",
    "time": 118,
    "translated_name": "Goodbye to Goodbyes!"
  },
  {
    "attribute": "Cool",
    "easy_notes": 96,
    "expert_notes": 581,
    "hard_notes": 403,
    "main_unit": "Î¼'s",
    "master_notes": null,
    "name": "NO EXIT ORION",
    "normal_notes": 215,
    "romaji_name": null,
    "time": 125,
    "translated_name": null
  },
  {
    "attribute": "Cool",
    "easy_notes": 109,
    "expert_notes": 459,
    "hard_notes": 344,
    "main_unit": "Î¼'s",
    "master_notes": null,
    "name": "Shangri-La Shower",
    "normal_notes": 217,
    "romaji_name": "",
    "time": 128,
    "translated_name": null
  },
  {
    "attribute": "Pure",
    "easy_notes": 108,
    "expert_notes": 513,
    "hard_notes": 367,
    "main_unit": "Î¼'s",
    "master_notes": null,
    "name": "æ¥æã­ãã³ãã£ãã¯",
    "normal_notes": 171,
    "romaji_name": "Shunjou Romantic",
    "time": 118,
    "translated_name": "Passionate Romantic"
  },
  {
    "attribute": "Pure",
    "easy_notes": 111,
    "expert_notes": 569,
    "hard_notes": 353,
    "main_unit": "Î¼'s",
    "master_notes": null,
    "name": "ãã¦ãã­ã¹ã­ãã¦ã",
    "normal_notes": 208,
    "romaji_name": "Ruteshi Kisuki Shiteru",
    "time": 127,
    "translated_name": "Ouy Evol I Love You"
  },
  {
    "attribute": "Smile",
    "easy_notes": 121,
    "expert_notes": 584,
    "hard_notes": 428,
    "main_unit": "Î¼'s",
    "master_notes": null,
    "name": "PSYCHIC FIRE",
    "normal_notes": 237,
    "romaji_name": null,
    "time": 120,
    "translated_name": null
  },
  {
    "attribute": "Pure",
    "easy_notes": 109,
    "expert_notes": 515,
    "hard_notes": 348,
    "main_unit": "Î¼'s",
    "master_notes": null,
    "name": "ããã¦æå¾ã®ãã¼ã¸ã«ã¯",
    "normal_notes": 205,
    "romaji_name": "Soshite Saigo no Page ni wa",
    "time": 123,
    "translated_name": "And on the Last Page"
  },
  {
    "attribute": "Smile",
    "easy_notes": 97,
    "expert_notes": 537,
    "hard_notes": 381,
    "main_unit": "Î¼'s",
    "master_notes": null,
    "name": "ã·ãã·ãã¼ã!",
    "normal_notes": 203,
    "romaji_name": "Puwa Puwa-O!",
    "time": 122,
    "translated_name": null
  },
  {
    "attribute": "Smile",
    "easy_notes": 156,
    "expert_notes": 584,
    "hard_notes": 382,
    "main_unit": "Î¼'s",
    "master_notes": null,
    "name": "Mermaid festa vol.2 ~Passionate~",
    "normal_notes": 261,
    "romaji_name": null,
    "time": 122,
    "translated_name": null
  },
  {
    "attribute": "Pure",
    "easy_notes": 156,
    "expert_notes": 553,
    "hard_notes": 325,
    "main_unit": "Î¼'s",
    "master_notes": null,
    "name": "ä¹å¥³å¼ããããå¡¾",
    "normal_notes": 248,
    "romaji_name": "Otome Shiki Renai Juku",
    "time": 107,
    "translated_name": "Maidenly Love Cram School"
  },
  {
    "attribute": "Cool",
    "easy_notes": 153,
    "expert_notes": 563,
    "hard_notes": 351,
    "main_unit": "Î¼'s",
    "master_notes": null,
    "name": "soldier game",
    "normal_notes": 246,
    "romaji_name": null,
    "time": 102,
    "translated_name": null
  },
  {
    "attribute": "Pure",
    "easy_notes": 156,
    "expert_notes": 579,
    "hard_notes": 355,
    "main_unit": "Î¼'s",
    "master_notes": null,
    "name": "åç½æ¥åãã§ã!",
    "normal_notes": 248,
    "romaji_name": "Kokuhaku Biyori, Desu!",
    "time": 104,
    "translated_name": "Its the Perfect Day for a Confession!"
  },
  {
    "attribute": "Smile",
    "easy_notes": 204,
    "expert_notes": 612,
    "hard_notes": 442,
    "main_unit": "Î¼'s",
    "master_notes": null,
    "name": "å¤¢ãªãå¤¢ã¯å¤¢ãããªã",
    "normal_notes": 301,
    "romaji_name": "Yume naki Yume wa Yume Janai",
    "time": 115,
    "translated_name": "A Dreamless Dream Isnt a Dream"
  },
  {
    "attribute": "Cool",
    "easy_notes": 239,
    "expert_notes": 532,
    "hard_notes": 432,
    "main_unit": "Î¼'s",
    "master_notes": null,
    "name": "Anemone heart",
    "normal_notes": 365,
    "romaji_name": null,
    "time": 108,
    "translated_name": null
  },
  {
    "attribute": "Pure",
    "easy_notes": 83,
    "expert_notes": 363,
    "hard_notes": 299,
    "main_unit": "Î¼'s",
    "master_notes": null,
    "name": "ãªãã¨ã³",
    "normal_notes": 168,
    "romaji_name": "Nawatobi",
    "time": 125,
    "translated_name": "Jumping Rope"
  },
  {
    "attribute": "Cool",
    "easy_notes": 207,
    "expert_notes": 598,
    "hard_notes": 463,
    "main_unit": "Î¼'s",
    "master_notes": null,
    "name": "Beat in Angel",
    "normal_notes": 311,
    "romaji_name": null,
    "time": 112,
    "translated_name": null
  },
  {
    "attribute": "Smile",
    "easy_notes": 231,
    "expert_notes": 650,
    "hard_notes": 468,
    "main_unit": "Î¼'s",
    "master_notes": null,
    "name": "ã«ãã·ãâ¡å¥³å­é",
    "normal_notes": 320,
    "romaji_name": "Nicopuri â¡ Joshidou",
    "time": 125,
    "translated_name": "Pretty Nicos â¡ Girly Ways"
  },
  {
    "attribute": "Pure",
    "easy_notes": 186,
    "expert_notes": 609,
    "hard_notes": 489,
    "main_unit": "Î¼'s",
    "master_notes": null,
    "name": "ç¡å­ã®è±å",
    "normal_notes": 303,
    "romaji_name": "Glass no Hanazono",
    "time": 120,
    "translated_name": "Garden of Glass"
  },
  {
    "attribute": "Pure",
    "easy_notes": 112,
    "expert_notes": null,
    "hard_notes": 359,
    "main_unit": "Î¼'s",
    "master_notes": null,
    "name": "åã®ãããã¯è¼ãã¦ãããã?",
    "normal_notes": 201,
    "romaji_name": "Kimi no kokoro wa kagayaite iru kai?",
    "time": 120,
    "translated_name": "Are our hearts shining?"
  },
  {
    "attribute": "Smile",
    "easy_notes": 121,
    "expert_notes": 592,
    "hard_notes": 451,
    "main_unit": "Î¼'s",
    "master_notes": null,
    "name": "WAO-WAO Powerful day!",
    "normal_notes": 222,
    "romaji_name": null,
    "time": 122,
    "translated_name": null
  },
  {
    "attribute": "Cool",
    "easy_notes": 116,
    "expert_notes": 447,
    "hard_notes": 350,
    "main_unit": "Aqours",
    "master_notes": null,
    "name": "ãã¤ã¹ã­ã ã£ãããã¤ã¸ã§ã¦ã!",
    "normal_notes": 198,
    "romaji_name": "Daisuki dattara Daijoubu!",
    "time": 102,
    "translated_name": "If You Love It, Itll Be Fine!"
  },
  {
    "attribute": "Cool",
    "easy_notes": 99,
    "expert_notes": 429,
    "hard_notes": 317,
    "main_unit": "Î¼'s",
    "master_notes": null,
    "name": "å¬ããããäºæ",
    "normal_notes": 181,
    "romaji_name": "Fuyu ga Kureta Yokan",
    "time": 127,
    "translated_name": "The Premonition that Winter Gave Me"
  },
  {
    "attribute": "Pure",
    "easy_notes": 85,
    "expert_notes": 415,
    "hard_notes": 283,
    "main_unit": "Aqours",
    "master_notes": null,
    "name": "å¤ç©ºã¯ãªãã§ãç¥ã£ã¦ãã®?",
    "normal_notes": 174,
    "romaji_name": "Yozora wa Nandemo Shitteru no?",
    "time": 125,
    "translated_name": "Does the Night Sky Know Everything?"
  },
  {
    "attribute": "Pure",
    "easy_notes": 70,
    "expert_notes": 306,
    "hard_notes": 217,
    "main_unit": "Î¼'s",
    "master_notes": null,
    "name": "æãåºä»¥ä¸ã«ãªãããã¦",
    "normal_notes": 106,
    "romaji_name": "Omoide Ijou ni Naritakute",
    "time": 108,
    "translated_name": "I Want It to Be More than a Memory"
  },
  {
    "attribute": "Smile",
    "easy_notes": 50,
    "expert_notes": null,
    "hard_notes": 200,
    "main_unit": "Î¼'s",
    "master_notes": null,
    "name": "æãã¦ãã°ããã¼ã! (Piano Mix)",
    "normal_notes": 100,
    "romaji_name": "Aishiteru Banzai! (Piano mix)",
    "time": 101,
    "translated_name": "I Love You, Hooray! (Piano mix)"
  },
  {
    "attribute": "Smile",
    "easy_notes": 129,
    "expert_notes": 532,
    "hard_notes": 390,
    "main_unit": "Î¼'s",
    "master_notes": null,
    "name": "æ°¸é ãã¬ã³ãº",
    "normal_notes": 212,
    "romaji_name": "Eien Friends",
    "time": 128,
    "translated_name": "Forever Friends"
  },
  {
    "attribute": "Smile",
    "easy_notes": 128,
    "expert_notes": 569,
    "hard_notes": 405,
    "main_unit": "Aqours",
    "master_notes": null,
    "name": "æ±ºãããHand in Hand",
    "normal_notes": 225,
    "romaji_name": "Kimeta yo Hand in Hand",
    "time": 109,
    "translated_name": "Weve Decided Hand in Hand"
  },
  {
    "attribute": "Pure",
    "easy_notes": 94,
    "expert_notes": 458,
    "hard_notes": 336,
    "main_unit": "Î¼'s",
    "master_notes": null,
    "name": "ç§ã®ããªãã®ç©ºé ã",
    "normal_notes": 189,
    "romaji_name": "Aki no Anata no Sora Tooku",
    "time": 99,
    "translated_name": "The Distant Autumn Sky with You"
  },
  {
    "attribute": "Cool",
    "easy_notes": 85,
    "expert_notes": 500,
    "hard_notes": 302,
    "main_unit": "Î¼'s",
    "master_notes": null,
    "name": "é¯è¦CROSSROADS",
    "normal_notes": 154,
    "romaji_name": "Sakkaku CROSSROADS",
    "time": 128,
    "translated_name": "Delusion CROSSROADS"
  }
]
);